config/routes.rb
Rails.application.routes.draw do
  resources :prizes
  resources :categories
  resources :episodes
  resources :sequences
  resources :shows
  resources :movies
  resources :subtitles
  resources :languages
  resources :classifications
  resources :contents
  resources :artists
  resources :plans
  resources :addresses
  resources :accounts
  resources :categoria
  resources :dashboard
  resources :select_account
  root 'home#index'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords",confirmations: "users/confirmations" }
  as :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user

    def full_name
      "#{nome}"
    end
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/categorium.rb
class Categorium < ApplicationRecord
    belongs_to :user, :class_name => 'User'
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :content
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/prize.rb
class Prize < ApplicationRecord
end

app/models/producer.rb
class Producer < ApplicationRecord
end

app/models/sequence.rb
class Sequence < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
    belongs_to :content
end

app/models/subtitle.rb
class Subtitle < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :plan, optional: true
  accepts_nested_attributes_for :plan, allow_destroy: true
  belongs_to :address, optional: true
  accepts_nested_attributes_for :address, allow_destroy: true
  has_many :accounts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.fetch(:content, {})
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/prizes_helper.rb
module PrizesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>